service: chat-gpt-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: RebeccaPersonal
  region: af-south-1

plugins:
  - serverless-offline

functions:
  handler:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /
          method: post
